# Generated by hand for antg-planning system

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='reference_mac_ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
