# Generated by Django 5.2.6 on 2026-05-19 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The organisational department this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='UserAccountManager.department'),
        ),
        migrations.CreateModel(
            name='PermissionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Confidential", "Secret"', max_length=64)),
                ('ranking', models.PositiveSmallIntegerField(help_text='Higher value = higher clearance.  Must be unique within its department.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_levels', to='UserAccountManager.department')),
            ],
            options={
                'ordering': ['department', 'ranking'],
                'unique_together': {('department', 'ranking')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_level',
            field=models.ForeignKey(blank=True, help_text='The access tier assigned to this user within their department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='UserAccountManager.permissionlevel'),
        ),
    ]
