# Generated by Django 6.0.3 on 2026-05-21 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def add_uuid_column_if_missing(apps, schema_editor):
    # Check if 'uuid' column exists in 'UserAccountManager_department'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_name = 'UserAccountManager_department' AND column_name = 'uuid'
        """)
        exists = cursor.fetchone()[0] > 0

    if not exists:
        # Run SQL to add column safely.
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "UserAccountManager_department" ADD COLUMN "uuid" UUID NULL UNIQUE;')
            
        Department = apps.get_model('UserAccountManager', 'Department')
        for obj in Department.objects.all():
            obj.uuid = uuid.uuid4()
            obj.save(update_fields=['uuid'])
            
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "UserAccountManager_department" ALTER COLUMN "uuid" SET NOT NULL;')


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0002_department_profile_department_permissionlevel_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_uuid_column_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='department',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable public identifier used as the key in department_access JSON maps.', unique=True),
                ),
            ]
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('ROLE_TOGGLE', 'Role Toggle')], db_index=True, max_length=20)),
                ('target_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('PERMISSION_LEVEL', 'Permission Level'), ('USER', 'User')], db_index=True, help_text='The model that was modified.', max_length=30)),
                ('target_id', models.CharField(help_text='Primary key or UUID of the affected object.', max_length=128)),
                ('details', models.JSONField(default=dict, help_text='Before/after diff or human-readable change description.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The admin user who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]

