# Generated by Django 6.0.3 on 2026-05-21 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=1024)),
                ('source_document_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('is_trashed', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_access', models.JSONField(blank=True, default=dict, help_text='Access control matrix. Keys are Department UUIDs (strings), values are the minimum ranking integer required for that department. A department absent from this map has no access.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drive.driveitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=1024)),
                ('version', models.PositiveIntegerField()),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drive.driveitem')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='driveitem',
            index=models.Index(fields=['owner', 'parent', 'is_trashed'], name='drive_drive_owner_i_e9f9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='driveitem',
            index=models.Index(fields=['owner', 'item_type', 'is_trashed'], name='drive_drive_owner_i_48df9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('drive_item', 'version')},
        ),
    ]
