# Generated by Django 6.0.3 on 2026-04-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driveitem',
            new_name='drive_drive_owner_i_e9f9f3_idx',
            old_name='drive_drivei_owner_i_61e7fb_idx',
        ),
        migrations.RenameIndex(
            model_name='driveitem',
            new_name='drive_drive_owner_i_48df9f_idx',
            old_name='drive_drivei_owner_i_05a2c7_idx',
        ),
    ]
