# Generated by Django 6.0.3 on 2026-04-09 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=1024)),
                ('version', models.PositiveIntegerField()),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drive.driveitem')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('drive_item', 'version')},
            },
        ),
    ]
