# Generated by Django 5.2.6 on 2026-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_fileversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveitem',
            name='department_access',
            field=models.JSONField(blank=True, default=dict, help_text='Access control matrix. Keys are Department UUIDs (strings), values are the minimum ranking integer required for that department. A department absent from this map has no access.'),
        ),
    ]
