# Generated by Django 6.0.3

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('notification_type', models.CharField(db_index=True, default='generic', max_length=64)),
                ('milestone_id', models.UUIDField(blank=True, null=True)),
                ('milestone_title', models.CharField(blank=True, max_length=255)),
                ('milestone_status', models.CharField(blank=True, max_length=32)),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('plan_title', models.CharField(blank=True, max_length=255)),
                ('reference_document_id', models.CharField(blank=True, max_length=255)),
                ('reference_filename', models.CharField(blank=True, max_length=512)),
                ('reference_mac_ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_4c5b72_idx')],
            },
        ),
    ]
